name: Indispensable
version: '${project.version}'
main: be.chenko.indispensable.Indispensable
api-version: 1.19
authors: [ TerroFlys, Lexdarco ]
description: An indispensable plugin for MC spigot servers
website: www.chenko.be
commands:
  home:
    description: Test command to see if the plugin works
    usage: /<command>
    permission: indispensable.command.home
  spawn:
    description: Go to the world spawn
    usage: /<command>
    permission: indispensable.command.spawn
  setspawn:
    description: Set the world spawn
    usage: /<command>
    permission: indispensable.command.setspawn
  sethome:
    description: Set home location
    usage: /<command>
    permission: indispensable.command.sethome
  god:
    description: You will become invincible!
    usage: /<command> <player>
    permission: indispensable.command.god
  tpa:
    description: Ask to be teleported to another player!
    usage: /<command> <player>
    permission: indispensable.command.tpa
  tpaccept:
    description: Accept the teleport !
    usage: /<command>
    permission: indispensable.command.tpaccept
    aliases:
      - tpyes
  tpdeny:
    description: Deny the teleport !
    usage: /<command>
    permission: indispensable.command.tpdeny
    aliases:
      - tpno
  heal:
    description: Heal yourself or someone else!
    usage: /<command> <player>
    permission: indispensable.command.heal
  healeffect:
    description: Heal yourself or someone else, this also removes any active status effects!
    usage: /<command> <player>
    permission: indispensable.command.healeffect
    aliases:
      - heale
      - healeff
      - healeffects
  voteday:
    description: Vote for the time to be day!
    usage: /<command>
    permission: indispensable.command.voteday
  votenight:
    description: Vote for the time to be night!
    usage: /<command>
    permission: indispensable.command.votenight